package ee.tenman.portfolio.configuration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration

@Configuration
@EnableConfigurationProperties(FundCurrencyOverridesProperties::class)
class FundCurrencyConfiguration
