version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    schedule:
      interval: quarterly
    open-pull-requests-limit: 5

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: quarterly
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: quarterly
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/cloudflare-bypass-proxy'
    schedule:
      interval: quarterly
    open-pull-requests-limit: 5
