services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: local

  app:
    image: nginx:alpine
    ports:
      - '61234:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  auth:
    container_name: auth
    image: ktenman/auth:latest
    environment:
      GOOGLE_CLIENT_ID: YOUR_GOOGLE_CLIENT_ID
      GOOGLE_CLIENT_SECRET: YOUR_GOOGLE_CLIENT_SECRET
