services:
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    environment:
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: local
      VISION_BASE64_ENCODED_KEY: ${VISION_BASE64_ENCODED_KEY}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      SERVER_PORT: 8081

  # Override the dev frontend with built frontend
  frontend:
    build:
      context: .
      dockerfile: ui/Dockerfile
    container_name: portfolio-frontend-e2e
    networks:
      - portfolio-network
    expose:
      - "80"
    ports: !reset []  # Force reset ports
    command: !reset nginx -g 'daemon off;'
    working_dir: !reset /usr/share/nginx/html
    volumes: !reset []  # Force reset volumes
    environment: !reset {}

  # Override the app service to use e2e nginx config
  app:
    image: nginx:alpine
    container_name: portfolio-app-e2e
    ports:
      - '61234:80'
    volumes:
      - ./nginx.e2e.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portfolio-network
    depends_on:
      - backend
      - frontend
      - auth

  auth:
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-YOUR_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET:-YOUR_GOOGLE_CLIENT_SECRET}
