FROM node:lts-slim as build

WORKDIR /app

RUN npm install

COPY ui/ ./ui
COPY tsconfig.json ./
COPY tsconfig.node.json ./
COPY vite.config.ts ./
COPY vite-env.d.ts ./

RUN npm run build && find /app -name "index.html"

RUN ls -la /app/dist/

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
