export const STORAGE_KEYS = {
  SELECTED_PLATFORMS: 'portfolio_selected_platforms',
  SELECTED_TRANSACTION_PLATFORMS: 'portfolio_selected_transaction_platforms',
  SELECTED_QUICK_DATE: 'portfolio_selected_quick_date',
  TRANSACTIONS_FROM_DATE: 'portfolio_transactions_from_date',
  TRANSACTIONS_UNTIL_DATE: 'portfolio_transactions_until_date',
  SHOW_ACTIVE_ONLY: 'portfolio_show_active_only',
  SELECTED_SUMMARY_PLATFORMS: 'portfolio_selected_summary_platforms',
  SUMMARY_CHART_RANGE: 'portfolio_summary_chart_range',
  PRICE_CHANGE_PERIOD: 'portfolio_price_change_period',
  SUMMARY_FILTERS_OPEN: 'portfolio_summary_filters_open',
  INSTRUMENTS_FILTERS_OPEN: 'portfolio_instruments_filters_open',
  TRANSACTIONS_FILTERS_OPEN: 'portfolio_transactions_filters_open',
  ETF_FILTERS_OPEN: 'portfolio_etf_filters_open',
} as const
