export enum Platform {
  AVIVA = 'AVIVA',
  BINANCE = 'BINANCE',
  COINBASE = 'COINBASE',
  IBKR = 'IBKR',
  LHV = 'LHV',
  LIGHTYEAR = 'LIGHTYEAR',
  SWEDBANK = 'SWEDBANK',
  TRADING212 = 'TRADING212',
  UNKNOWN = 'UNKNOWN',
}
