apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio
  labels:
    build-hash: local
  annotations:
    build-time: local
spec:
  template:
    metadata:
      labels:
        build-hash: local
      annotations:
        build-time: local
        kubectl.kubernetes.io/restartedAt: local
    spec:
      containers:
        - name: backend
          env:
            - name: TELEGRAM_BOT_ENABLED
              value: "false"
            - name: TRADING212_ENABLED
              value: "false"
            - name: BUILD_HASH
              value: "local"
            - name: BUILD_TIME
              value: "local"
