apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ktenman/portfolio-be:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/portfolio"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_PROFILES_ACTIVE
              value: "default"
            - name: VISION_ENABLED
              value: "true"
            - name: TELEGRAM_BOT_ENABLED
              value: "true"
            - name: VISION_BASE64_ENCODED_KEY
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: VISION_BASE64_ENCODED_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: portfolio-secrets
                  key: TELEGRAM_BOT_TOKEN
          # Essential health check for zero downtime
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: portfolio
spec:
  ports:
    - port: 8080
  selector:
    app: backend
