apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: portfolio
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  # OAuth credentials
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
  GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"

  # Application secrets
  ALLOWED_EMAILS: "${ALLOWED_EMAILS}"
  VISION_BASE64_ENCODED_KEY: "${VISION_BASE64_ENCODED_KEY}"
  TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"

  # External monitoring - this was missing from your K8s setup!
  HEALTHCHECK_URL: "${HEALTHCHECK_URL}"
