apiVersion: v1
kind: Secret
metadata:
  name: portfolio-secrets
  namespace: portfolio
type: Opaque
stringData:
  POSTGRES_USER: "${POSTGRES_USER}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
  ALLOWED_EMAILS: "${ALLOWED_EMAILS}"
  VISION_BASE64_ENCODED_KEY: "${VISION_BASE64_ENCODED_KEY}"
  TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
