CREATE TABLE collection_operation (
  collection_key VARCHAR(64) PRIMARY KEY,
  initialized_at TIMESTAMP WITH TIME ZONE NOT NULL,
  attempted_items INTEGER NOT NULL DEFAULT 0,
  fetched_items INTEGER NOT NULL DEFAULT 0,
  persisted_items INTEGER NOT NULL DEFAULT 0,
  failed_items INTEGER NOT NULL DEFAULT 0,
  last_attempt TIMESTAMP WITH TIME ZONE,
  last_completion TIMESTAMP WITH TIME ZONE,
  last_persistence TIMESTAMP WITH TIME ZONE,
  last_full_success TIMESTAMP WITH TIME ZONE,
  consecutive_empty_runs INTEGER NOT NULL DEFAULT 0,
  duration_seconds DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE collection_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_key VARCHAR(64) NOT NULL REFERENCES collection_operation(collection_key),
  symbol VARCHAR(255) NOT NULL,
  initialized_at TIMESTAMP WITH TIME ZONE NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  last_success TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT collection_item_key_symbol_unique UNIQUE (collection_key, symbol)
);
