CREATE TABLE fund_allocation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fund_isin VARCHAR(12) NOT NULL,
  as_of_date DATE NOT NULL,
  source_url TEXT NOT NULL,
  reported_total NUMERIC(7, 4) NOT NULL,
  underlying_isin VARCHAR(12) NOT NULL,
  underlying_name VARCHAR(255) NOT NULL,
  weight NUMERIC(7, 4) NOT NULL,
  repaired_from VARCHAR(12),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  version BIGINT NOT NULL DEFAULT 0,
  CONSTRAINT fund_allocation_source_isin_unique UNIQUE (source_url, underlying_isin)
);

CREATE INDEX idx_fund_allocation_fund_date ON fund_allocation (fund_isin, as_of_date);
