name: Docker Push

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME_BACKEND: ktenman/portfolio-be
  DOCKER_IMAGE_NAME_FRONTEND: ktenman/portfolio-fe
  DOCKER_IMAGE_NAME_MARKET_PRICE_TRACKER: ktenman/market-price-tracker

jobs:
  build-and-push:
    name: 🐳 Build & Push Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            dockerfile: ./Dockerfile.backend
            image: ${{ env.DOCKER_IMAGE_NAME_BACKEND }}
            context: .
          - name: frontend
            dockerfile: ./Dockerfile.frontend
            image: ${{ env.DOCKER_IMAGE_NAME_FRONTEND }}
            context: .
          - name: market-price-tracker
            dockerfile: ./market-price-tracker/Dockerfile
            image: ${{ env.DOCKER_IMAGE_NAME_MARKET_PRICE_TRACKER }}
            context: ./market-price-tracker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push ${{ matrix.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}:latest
