name: Docker Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    name: 🐳 Build & Push
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            dockerfile: ./Dockerfile.backend
            image: ktenman/portfolio-be
            context: .
          - name: frontend
            dockerfile: ./Dockerfile.frontend
            image: ktenman/portfolio-fe
            context: .
          - name: market-price-tracker
            dockerfile: ./market-price-tracker/Dockerfile
            image: ktenman/market-price-tracker
            context: ./market-price-tracker
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4.0.0
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.1.0
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push ${{ matrix.name }} image
        uses: docker/build-push-action@v5.0.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ${{ matrix.image }}:${{ github.event.inputs.version }}
